// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'cover-view-image-alt'
  | 'cover-view-switch-to-grid'
  | 'cover-view-switch-to-list'
  | 'pref-enable-grid-view'
  | 'pref-fetch-isbn-cover'
  | 'pref-fetch-metadata-cover'
  | 'pref-help'
  | 'pref-show-authors'
  | 'pref-tile-size'
  | 'pref-tile-size-percent'
  | 'pref-title'
  | 'prefs-title';
