// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'cover-view-image-alt'
  | 'cover-view-switch-to-grid'
  | 'cover-view-switch-to-list'
  | 'pref-help'
  | 'pref-show-authors'
  | 'pref-title'
  | 'prefs-title';
