// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableGridView": boolean;
      "showCreators": boolean;
      "showTitles": boolean;
      "showYears": boolean;
      "tileSize": number;
      "fetchISBNCover": boolean;
      "fetchMetadataCover": boolean;
    };
  }
}
